---
sudo: required
language: node_js
node_js:
  - "8"
services:
  - docker
addons:
  apt:
    packages:
      # needed to build o2r-meta
      - gcc
      - g++
      - python3
      - python3-dev
      - python3-pip
      - libxml2-dev
      - libxslt1-dev
      - libgdal-dev
      - python3-gdal
before_install:
  - docker --version
  - python --version
  - python3 --version
  - docker pull o2rproject/o2r-muncher:latest
  - docker pull mongo:3.4
  - sudo pip3 install --upgrade pip
  - sudo pip3 install bagit
  - git clone --depth 1 -b master https://github.com/o2r-project/o2r-meta.git $HOME/meta
  - cd $HOME/meta
  - sudo pip3 install -r requirements.txt
  - export LOADER_META_TOOL_EXE="python3 $HOME/meta/o2rmeta.py"
  - export LOADER_META_EXTRACT_MAPPINGS_DIR="$HOME/meta/broker/mappings"
  - cd $TRAVIS_BUILD_DIR
  # https://github.com/npm/npm/issues/17858
  - rm package-lock.json
  - npm i -g npm@5.4.2
  - npm --version
install:
  - npm install
before_script:
  - docker run --name mongodb -d -p 27017:27017 mongo:3.4
  - docker run --name testmuncher -d -p 8080:8080 --link mongodb:mongodb -v $HOME:/tmp/o2r -e LOADER_MONGODB=mongodb://mongodb:27017 -e DEBUG=* o2rproject/o2r-muncher:latest
  - sleep 10
script:
  - DEBUG=loader,loader:* LOADER_BASEPATH=$HOME/ npm start &
  #- DEBUG=* npm test
  - DEBUG=* npm test
after_failure:
  - sleep 5
  - docker logs testmuncher
